const COMMANDS = ['PLACE', 'MOVE', 'LEFT', 'RIGHT', 'REPORT'];
const DIRECTIONS = ['NORTH', 'EAST', 'SOUTH', 'WEST'];
const MAX_COORDINATE = 4;
const MIN_COORDINATE = 0;
export { COMMANDS, DIRECTIONS, MAX_COORDINATE, MIN_COORDINATE };